FROM ubuntu:20.04

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y build-essential wget zlib1g-dev libncurses5-dev libncursesw5-dev libbz2-dev liblzma-dev

# Install Samtools
WORKDIR /software
RUN wget https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2 && \
    tar -xvf samtools-1.18.tar.bz2 && \
    cd samtools-1.18 && \
    ./configure && \
    make && \
    make install

RUN rm -r samtools-1.18 samtools-1.18.tar.bz2
WORKDIR /
